#!/usr/bin/bash
#Get all the removable mounted drives

unmountables=$(lsblk -lp | awk '/^[\/A-Za-z0-9]+ +[0-9]+:[0-9]+ +1 +[0-9]+\.?[0-9]+?[GMK] +0 +part +\// {print $1, "("$4")"}')

chosen=$(echo "$unmountables" | dmenu -i -p "Unmount:" | awk '{print $1}')

[[ -z "$chosen" ]] && exit 1

sudo umount $chosen
